defaults:
  - problem: mazes_zind
  - override problem/model: dt_net_2d_parallel
  - override hydra/job_logging: custom
  - _self_

hydra:
  run:
    dir: ./outputs/${name}/testing-${run_id}
  job_logging:
    handlers:
      file:
        filename: testing.log

name: testing_zind

problem:
  model:
    test_iterations:
      low: 20
      high: 140
    model_path: outputs/training_default/training-unlost-Tamar

quick_test: True
termination_condition: True
time_evaluation: False
accuracy_evaluation: False
